services:
  db:
    image: postgres:15-alpine
    container_name: zg-db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url_shortener
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U url_shortener -d url_shortener"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zg-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: url_shortener
      SPRING_DATASOURCE_PASSWORD: url_shortener
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

volumes:
  db_data: