services:
  # Static frontend (Angular) served via Render CDN
  - type: web
    name: zg-frontend
    env: static
    rootDir: frontend
    branch: main
    buildCommand: yarn build
    staticPublishPath: dist/frontend/browser
    envVars:
      # Defina este valor no dashboard ao criar o Blueprint (URL pública do backend)
      - key: API_BASE_URL
        sync: false
    # SPA fallback: reescreve rotas para index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Spring Boot) como Web Service usando Docker
  - type: web
    name: zg-backend
    env: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    branch: main
    healthCheckPath: /actuator/health/readiness
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false